### PR TITLE
Change for packer 0.8.1, now plugin build successfully.

### PR DESCRIPTION
**Pull request by mightydok**

### CODE REVIEW

**Comment by mightydok** [comment]
Oops, tests need fix too.

**Comment by StefanScherer** [comment]
@mightydok please run a `make format` and commit any diffs.

**Comment by mightydok** [comment]
@StefanScherer done

**Comment by StefanScherer** [comment]
@mightydok Thanks. Compiling works! I'm currently testing a new Windows binary in my basebox-slave pipeline.

**Comment by StefanScherer** [comment]
@frapposelli LGTM!

**Comment by frapposelli** [comment]
Thanks @mightydok for the patch.

and thanks @StefanScherer for the review!

**Pull request merged**
